name: Update Age in README

on:
  schedule:
    - cron: '0 0 20 11 *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update age in README
        run: |
          CURRENT_YEAR=$(date +%Y)
          BIRTH_YEAR=1999
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          sed -i "s/tenho .* anos/tenho $AGE anos/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Atualiza a idade no README"
          git push
